/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_USB4Device */

#ifndef _Included_main_USB4Device
#define _Included_main_USB4Device
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_USB4Device
 * Method:    initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_USB4Device_initialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
