/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_TurtleTracker */

#ifndef _Included_main_TurtleTracker
#define _Included_main_TurtleTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_TurtleTracker
 * Method:    read
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_main_TurtleTracker_read
  (JNIEnv *, jclass, jint);

/*
 * Class:     main_TurtleTracker
 * Method:    reset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_main_TurtleTracker_reset
  (JNIEnv *, jclass, jint);

/*
 * Class:     main_TurtleTracker
 * Method:    setUpTracker
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_main_TurtleTracker_setUpTracker
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
